user:
  email:
    min_length: 10
    max_length: 255
    regex_format: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  name:
    max_length: 50
  password:
    min_length: 6
subject:
  name:
    max_50: 50
  content:
    max_1000: 1000
question:
  content:
    max_1000: 1000
answer:
  content:
    max_1000: 1000
paging:
  per_page_5: 5
  per_page_15: 15
  per_page_choose_5: ["5", 5]
  per_page_choose_10: ["10", 10]
  per_page_choose_15: ["15", 15]
